### ISSUE TITLE
Made a 'ru_ru' translation

### ISSUE THREAD

**Issue by BrickerMoss** [Team-Abode/verdance#16]
The 'ru_ru' (russian) translation file: [ru_ru.json](https://github.com/user-attachments/files/16487080/ru_ru.json)

P.S. First time using github, i hope this is how i should submit things lmao

**Comment by ExDrill** [comment]
Thanks for the contribution! You should look into how pull requests on GitHub work or any future Verdance updates. (Or just other mods in general)
