### ISSUE TITLE
Cantaloupe Stem block not tagged as `minecraft:crops` in 1.21 Fabric

### ISSUE THREAD

**Issue by TelepathicGrunt** [Team-Abode/verdance#21]
Can you please tag your crop blocks in `minecraft:crops` block tag? It'll allow bees to grow your crop and allow better mod compat like my mod that will autogrow crops in that tag too.
https://github.com/misode/mcmeta/blob/data-json/data/minecraft/tags/block/crops.json

Specifically it seem `verdance:cantaloupe_stem` block is an issue

**Comment by ExDrill** [comment]
Thank you for reminding us, this will be addressed in the next release.
